CREATE TABLE users (
    username VARCHAR(50) COLLATE utf8mb4_general_ci NOT NULL PRIMARY KEY,
    password VARCHAR(500) NOT NULL,
    enabled BOOLEAN NOT NULL
);

CREATE TABLE authorities (
    username VARCHAR(50) COLLATE utf8mb4_general_ci NOT NULL,
    authority VARCHAR(50) COLLATE utf8mb4_general_ci NOT NULL,
    CONSTRAINT fk_authorities_users FOREIGN KEY (username) REFERENCES users (username)
);

CREATE UNIQUE INDEX ix_auth_username ON authorities (username, authority);

select * from users;

ALTER TABLE users MODIFY authorities VARCHAR(255) DEFAULT 'ROLE_USER';
UPDATE users SET password = "flaksdjfldsjsalkdjf", firstname = "yoooro", lastname = "forgerrr", email = "yor@gmail.com" WHERE id = 3;


select * from authorities;

CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL,
    password VARCHAR(100) NOT NULL,
    firstname VARCHAR(50) NOT NULL,
    lastname VARCHAR(50) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    authorities VARCHAR(255) NOT NULL
);

CREATE TABLE purchase_orders (
    purchase_id VARCHAR(255) NOT NULL PRIMARY KEY,
    user_id INT NOT NULL,
    items_purchased VARCHAR(200) NOT NULL,
    item_ids VARCHAR(200) NOT NULL,
    amount BIGINT NOT NULL,
    email VARCHAR(255),
    receipt_url VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_user
        FOREIGN KEY (user_id) 
        REFERENCES users(id)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);




select * from  purchase_orders;
select * from products;
select * from users;
select * from purchase_orders where user_id = "2";

select * from products;

SELECT * FROM products WHERE LOWER(description) LIKE LOWER('%gpt%');
select * from products where id = 2;
select * from product_reviews;
        SELECT purchase_id, product_id, product_name, user_id, rating, review FROM product_reviews    ;



CREATE TABLE product_reviews (
    id INT AUTO_INCREMENT PRIMARY KEY,
    purchase_id VARCHAR(50),
    product_id INT,
    product_name VARCHAR(255),
    user_id INT,
    rating INT,
    review TEXT,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_purchase FOREIGN KEY (purchase_id) REFERENCES purchase_orders(purchase_id) 
        ON DELETE CASCADE 
        ON UPDATE CASCADE,
    CONSTRAINT fk_review_product FOREIGN KEY (product_id) REFERENCES products(id) 
        ON DELETE CASCADE 
        ON UPDATE CASCADE,
    CONSTRAINT fk_review_user FOREIGN KEY (user_id) REFERENCES users(id) 
        ON DELETE CASCADE 
        ON UPDATE CASCADE
);

CREATE TABLE products(
   id          INTEGER  NOT NULL PRIMARY KEY 
  ,productname VARCHAR(100) NOT NULL
  ,description VARCHAR(714) NOT NULL
  ,tags        VARCHAR(40) NOT NULL
  ,url         VARCHAR(500) NOT NULL
  ,price       FLOAT
  ,rating      INTEGER  NOT NULL
  ,image       VARCHAR(250) NOT NULL
);
INSERT INTO products(id,productname,description,tags,url,price,rating,image) VALUES (1,'Claude.ai','Claude AI is a chatty AI assistant that excels at conversation and written tasks. It can summarize information, brainstorm ideas, and even edit your writing. While it can''t understand everything perfectly, Claude''s ability to hold natural conversations and complete tasks makes it a helpful tool for students, writers, and anyone who wants an AI sidekick.','Chatbot','https://claude.ai/',20.00,4,'https://aigc.sgp1.cdn.digitaloceanspaces.com/1.png');
INSERT INTO products(id,productname,description,tags,url,price,rating,image) VALUES (2,'ChatGPT','ChatGPT is a powerful AI tool that can chat naturally and handle written tasks. It can condense information, write different creative content formats, and even translate languages. However, keep in mind it might stumble with factual accuracy and tricky requests. Despite this, ChatGPT''s ability to chat and help with writing makes it a valuable asset for anyone who wants to understand information faster or get a boost in their creative writing.','Chatbot','https://openai.com/chatgpt/',20.00,4,'https://aigc.sgp1.cdn.digitaloceanspaces.com/2.png');
INSERT INTO products(id,productname,description,tags,url,price,rating,image) VALUES (136,'Copilot','With the new Copilot app, you can search and access your Copilot anytime, anywhere. Ask your Copilot anything you want, from trivia questions to creating images. Like a friend, Copilot will give you quick and helpful answers, along with suggestions for what to do next. You can even use voice to search or chat, and your history and preferences will sync across all your devices.','Chatbot','https://www.microsoft.com/en-us/microsoft-copilot/learn?form=MA13FV',21.62,4,'https://aigc.sgp1.cdn.digitaloceanspaces.com/136.jpg');
INSERT INTO products(id,productname,description,tags,url,price,rating,image) VALUES (137,'Zapier Central','Over a decade ago, Zapier launched with a simple idea that computers should do more work for you. Today, over 2.2 million businesses use Zapier to automate 2 billion tasks every month. Central puts you in the driver seat to automate even more work with the help of your friendly AI bots.','Chatbot','https://zapier.com/central',29.99,4,'https://aigc.sgp1.cdn.digitaloceanspaces.com/137.jpg');
INSERT INTO products(id,productname,description,tags,url,price,rating,image) VALUES (3,'LearnPrompting','Learn Prompting teaches you to talk to AI like ChatGPT. Their free course explains how to craft instructions (prompts) to get AI to do what you want, with real-world examples. They even have a competition to improve AI safety!','Prompt','https://learnprompting.org/zh-Hans/',39.00,3,'https://aigc.sgp1.cdn.digitaloceanspaces.com/image-0.png');
INSERT INTO products(id,productname,description,tags,url,price,rating,image) VALUES (4,'LMSYS','LMSYS is a powerful platform that enables users to engage in conversations with various open large language models. With its diverse range of chat assistants such as Vicuna, a fine-tuned chatbot impressing GPT-4, and FastChat-T5, a chat assistant fine-tuned from FLAN-T5, users can experience high-quality interactions and access the capabilities of state-of-the-art language models. LMSYS offers an interactive and versatile environment for users to leverage the potential of open language models for a wide range of applications and research purposes.','Big model,Open source','https://chat.lmsys.org/',0.00,3,'https://aigc.sgp1.cdn.digitaloceanspaces.com/image-3.png');
INSERT INTO products(id,productname,description,tags,url,price,rating,image) VALUES (5,'Wiseone','Wiseone is a browser extension that offers a new way of reading and exploring information online. The new AI-powered browser extension enriches your online reading experience by helping you simplify information, effortlessly master any subject you''re reading and have easier access to factual information.','Pluggin','https://chrome.google.com/webstore/detail/wiseone-%E2%80%93-ai-powered-read/paodpkkacimmkacaecjmhdncjgjepcai/related',0.00,5,'https://aigc.sgp1.cdn.digitaloceanspaces.com/image-4.png');
INSERT INTO products(id,productname,description,tags,url,price,rating,image) VALUES (6,'Consensus','For academic research, Consensus is a search engine powered by AI. It digs through over 200 million scientific papers to find the best ones for your topic. Using advanced AI and custom search tools, Consensus helps researchers zoom in on relevant and dependable sources. It offers features like AI summaries of topics, citation suggestions, and helpful insights to save researchers time. Universities, students, medical professionals, and researchers worldwide all use Consensus.','Search engine','https://consensus.app/',8.90,3,'https://aigc.sgp1.cdn.digitaloceanspaces.com/image-5.png');
INSERT INTO products(id,productname,description,tags,url,price,rating,image) VALUES (7,'PixAI','PixAI.art lets you create digital art with the help of AI. It focuses on anime-style characters, realistic portraits, and wallpapers. This platform is great for anime fans, artists, and anyone who wants to add a creative touch to their digital projects. PixAI offers a range of AI art styles to pick from, letting you experiment and find the perfect look for your artwork. They even have editing tools, a marketplace for models, and art competitions to keep things interesting.','2D','https://pixai.art/',0.00,3,'https://aigc.sgp1.cdn.digitaloceanspaces.com/image-7.png');
INSERT INTO products(id,productname,description,tags,url,price,rating,image) VALUES (8,'Warp','Warp is a reimagined terminal designed to boost developer productivity. Built with Rust for speed and efficiency, Warp offers a modern take on the classic command line. It features a powerful input editor with autocompletion, and a unique block system for organizing and sharing frequently used commands. Warp integrates AI to help debug errors and even generate commands based on your intent. For collaborative work, Warp Drive allows teams to create and share templated commands in the cloud.','Software,Programming','https://www.warp.dev/',15.00,3,'https://aigc.sgp1.cdn.digitaloceanspaces.com/image-7.png');
INSERT INTO products(id,productname,description,tags,url,price,rating,image) VALUES (9,'GPTbase','GPTBase AI is a remarkable platform that allows users to create chatbots using their own documents, enabling customized and personalized conversational experiences. Additionally, the platform offers a wide range of publicly available bots, including notable ones like naval and Atomic Habits, that provide valuable conversation experiences on various topics. With its versatility and access to diverse conversation models, GPTBase AI empowers users to build engaging and informative chatbot interactions.','Chatbot','https://gptbase.ai/',0.00,2,'https://aigc.sgp1.cdn.digitaloceanspaces.com/image-8.png');
INSERT INTO products(id,productname,description,tags,url,price,rating,image) VALUES (10,'Cursor','Cursor is a ChatGPT-style AI programming IDE. It combines natural language processing capabilities with traditional programming tools to create an interactive and intuitive coding experience.','Programming,Software','https://www.cursor.so/',0.00,5,'https://aigc.sgp1.cdn.digitaloceanspaces.com/image-9.png');
INSERT INTO products(id,productname,description,tags,url,price,rating,image) VALUES (11,'AIPRM','AIPRM stands for Artificial Intelligence Prompts and Responses Manager. It''s a Google Chrome extension that adds a list of curated prompt templates to the ChatGPT platform.','Prompt,Pluggin','https://chrome.google.com/webstore/detail/aiprm-for-chatgpt/ojnbohmppadfgpejeebfnmnknjdlckgj',0.00,3,'https://aigc.sgp1.cdn.digitaloceanspaces.com/image-10.png');
INSERT INTO products(id,productname,description,tags,url,price,rating,image) VALUES (12,'Typeset','AI paper reading and reading assistance, can view popular papers, conversational research, supports multiple languages, and automatically generates brainstorming questions.','PDF','https://typeset.io/',0.00,4,'https://aigc.sgp1.cdn.digitaloceanspaces.com/image-11.png');
INSERT INTO products(id,productname,description,tags,url,price,rating,image) VALUES (13,'ShareGPT','A GPT conversation sharing website, even Google trained Bard uses data from here.','Prompt','https://sharegpt.com/',0.00,3,'https://aigc.sgp1.cdn.digitaloceanspaces.com/image-12.png');
INSERT INTO products(id,productname,description,tags,url,price,rating,image) VALUES (14,'Creativindie','extensive list of 644 imaginative ideas for generating text-to-image concepts. With this epic compilation, users can unlock a world of creative possibilities, inspiring them to explore unique and unconventional combinations of text and visuals. Whether for artistic endeavors, storytelling, or design projects, this site provides a treasure trove of wild and fascinating prompts to spark your imagination.','Midjourney,Prompt','https://www.creativindie.com/best-midjourney-prompts-an-epic-list-of-crazy-text-to-image-ideas/',0.00,3,'https://aigc.sgp1.cdn.digitaloceanspaces.com/image-13.png');
INSERT INTO products(id,productname,description,tags,url,price,rating,image) VALUES (15,'OpenPrompt','Open-source prompt sharing and testing platform, Github account registration can be used directly without entering a key.','Prompt','https://openprompt.co/',4.00,3,'https://aigc.sgp1.cdn.digitaloceanspaces.com/image-14.png');
INSERT INTO products(id,productname,description,tags,url,price,rating,image) VALUES (16,'RegexAI','AI generates regular expressions, very easy to use.','Programming','https://regex.ai/',0.00,3,'https://aigc.sgp1.cdn.digitaloceanspaces.com/image-15.png');
INSERT INTO products(id,productname,description,tags,url,price,rating,image) VALUES (17,'Story AI','Story AI is a captivating platform that enables users to create their own unique stories with the help of artificial intelligence. With Story AI, users have the freedom to choose any topic or theme they desire and provide prompts to guide the AI in crafting a personalized narrative. By combining human creativity with the power of AI, Story AI opens up a world of endless storytelling possibilities, allowing users to unleash their imagination and bring their ideas to life.','Story writing','https://storyai.cc/',0.00,3,'https://aigc.sgp1.cdn.digitaloceanspaces.com/image-18.png');
INSERT INTO products(id,productname,description,tags,url,price,rating,image) VALUES (18,'Llamahub','A third-party open-source tool for calling LLM to achieve document semantic dialogue.','Programming,Source code','https://llamahub.ai/',0.00,3,'https://aigc.sgp1.cdn.digitaloceanspaces.com/image-18.png');
INSERT INTO products(id,productname,description,tags,url,price,rating,image) VALUES (19,'PromptBase','Sell your prompts, including Midjounery, SD, Dall·E, GPT, and so on.','Image AI,Midjourney','https://promptbase.com/',0.00,3,'https://aigc.sgp1.cdn.digitaloceanspaces.com/image-19.png');
INSERT INTO products(id,productname,description,tags,url,price,rating,image) VALUES (20,'Stable Diffusion','Stable Diffusion is a latent text-to-image diffusion model capable of generating photo-realistic images given any text input, cultivates autonomous freedom to produce incredible imagery, empowers billions of people to create stunning art within seconds.','Illustration','https://stablediffusionweb.com/',50.00,5,'https://aigc.sgp1.cdn.digitaloceanspaces.com/image-20.png');
INSERT INTO products(id,productname,description,tags,url,price,rating,image) VALUES (21,'Obsidian','The Obsidian Text Generator Plugin makes use of OpenAI, a powerful and affordable AI tool, to generate text using the GPT-3 Language Model. It''s an incredible tool to help writers, bloggers, or anyone else generate ideas, titles, outlines, or whole paragraphs, from within Obsidian.','Notes taking,Software','https://obsidian.md/',8.00,5,'https://aigc.sgp1.cdn.digitaloceanspaces.com/image-21.png');
INSERT INTO products(id,productname,description,tags,url,price,rating,image) VALUES (22,'Notion AI','Notion AI is available to all users. You can prompt AI using your space bar, highlighting text and selecting "Ask AI", or via slash commands. You must take action for AI to activate. It will not generate content or send requests to our AI providers unless you perform one of the actions above.','Writing,ChatGPT','https://www.notion.so/',0.00,5,'https://aigc.sgp1.cdn.digitaloceanspaces.com/image-22.png');
INSERT INTO products(id,productname,description,tags,url,price,rating,image) VALUES (23,'CopilotHub','GitHub Copilot started a new age of software development as an AI pair programmer that keeps developers in the flow by auto-completing comments and code. And less than two years since its launch, GitHub Copilot is already writing 46% of code and helps developers code up to 55% faster.','Conversation','https://app.copilothub.co/home',0.00,3,'https://aigc.sgp1.cdn.digitaloceanspaces.com/image-23.png');
INSERT INTO products(id,productname,description,tags,url,price,rating,image) VALUES (24,'OpenCat App','OpenCat is a native client software for OpenAI ChatGPT, providing a smoother and faster chat experience than web.','ChatGPT,Client side,App','https://apps.apple.com/us/app/opencat/id6445999201',0.00,5,'https://aigc.sgp1.cdn.digitaloceanspaces.com/image-24.png');
INSERT INTO products(id,productname,description,tags,url,price,rating,image) VALUES (25,'ChatDoc','ChatDOC lets you chat with PDFs and tables to quickly extract information and insights. Sources are cited for fact-checking, this is a ChatGPT based file-reading assistant. Unlike other AI file readers, ChatDOC can understand both tables and text!','Reading,PDF','https://chatdoc.com/',0.00,5,'https://aigc.sgp1.cdn.digitaloceanspaces.com/image-25.png');
INSERT INTO products(id,productname,description,tags,url,price,rating,image) VALUES (26,'BriefGPT','BriefGPT is a pre-trained language model based on natural language processing, capable of performing various NLP tasks such as text classification, question answering, and text generation. With its broad applicability, BriefGPT can effectively process and analyze text data, providing valuable insights and solutions across different NLP domains. Its versatility makes it a powerful tool for tackling diverse natural language processing tasks.','Information search','https://briefgpt.xyz/',0.00,3,'https://aigc.sgp1.cdn.digitaloceanspaces.com/image-26.png');
INSERT INTO products(id,productname,description,tags,url,price,rating,image) VALUES (27,'CivitAI','Civitai is an online platform that makes it easy for people to share and discover resources for creating AI art. Users can upload and share models that have been trained to generate art in a particular style, or browse and download models created by other users.','AI community,AI model','https://civitai.com/',0.00,4,'https://aigc.sgp1.cdn.digitaloceanspaces.com/image-27.png');
INSERT INTO products(id,productname,description,tags,url,price,rating,image) VALUES (28,'NovelAI','NovelAI is an online cloud-based, SaaS model, paid subscription service for AI-assisted storywriting and text-to-image synthesis, originally launched in beta on June 15, 2021, with the image generation feature later implemented on October 3, 2022.','Writing','https://novelai.net/',0.00,3,'https://aigc.sgp1.cdn.digitaloceanspaces.com/image-28.png');
INSERT INTO products(id,productname,description,tags,url,price,rating,image) VALUES (29,'Raycast AI','Raycast is a blazingly fast, totally extendable launcher. It lets you complete tasks, calculate, share common links, and much more.','ChatGPT,Software','https://www.raycast.com/ai',0.00,5,'https://aigc.sgp1.cdn.digitaloceanspaces.com/image-29.png');
INSERT INTO products(id,productname,description,tags,url,price,rating,image) VALUES (30,'Hotoke AI','A "mechanical Buddha" consultation website based on ChatGPT.','Phychology,ChatGPT','https://hotoke.ai/',0.00,3,'https://aigc.sgp1.cdn.digitaloceanspaces.com/image-30.png');
INSERT INTO products(id,productname,description,tags,url,price,rating,image) VALUES (31,'JasperAI','Jasper is the best AI writer and AI art generator for teams with over 3000 5-star reviews. Create blog posts, marketing copy, and AI-generated images fast.','Marketing,Commercial writing','https://www.jasper.ai/',0.00,3,'https://aigc.sgp1.cdn.digitaloceanspaces.com/image-31.png');
INSERT INTO products(id,productname,description,tags,url,price,rating,image) VALUES (32,'OpenAI Translator','The OpenAI Translator is a plugin developed for Trados Studio that uses the language models provided through the OpenAI API.','Translation tool,ChatGPT','https://chrome.google.com/webstore/detail/openai-translator/ogjibjphoadhljaoicdnjnmgokohngcc?hl=zh-CN',0.00,5,'https://aigc.sgp1.cdn.digitaloceanspaces.com/image-32.png');
INSERT INTO products(id,productname,description,tags,url,price,rating,image) VALUES (33,'Bifrost','Bifrost builds virtual worlds and synthetic datasets that artificial intelligence teams can use to train AI models for applications in areas such as gaming, the metaverse, mobility, robotics, space, and defense. AI teams all over the world struggle to find high-quality labeled training data at scale.','Figma,Programming','https://www.bifrost.so/',0.00,3,'https://aigc.sgp1.cdn.digitaloceanspaces.com/image-33.png');
INSERT INTO products(id,productname,description,tags,url,price,rating,image) VALUES (34,'Writesonic','"Writesonic is an AI writer that creates SEO-friendly content for blogs, Facebook ads, Google ads, and Shopify for free. Our paraphrasing tool lets. you rephrase entire articles instantly."','Marketing,Commercial writing','https://writesonic.com/',0.00,3,'https://aigc.sgp1.cdn.digitaloceanspaces.com/image-34.png');
INSERT INTO products(id,productname,description,tags,url,price,rating,image) VALUES (35,'Magician','Magician is a Figma plugin that uses AI to help you do everything. From copywriting to generating unique icons from text. Like magic! ✨ Magician has 3 main pillars and functionality: 🎨 Magic Icon - text-to-image unique icons.','Figma,Design','https://magician.design/',0.00,3,'https://aigc.sgp1.cdn.digitaloceanspaces.com/image-35.png');
INSERT INTO products(id,productname,description,tags,url,price,rating,image) VALUES (36,'Midjourney','Midjourney is a generative artificial intelligence program and service created and hosted by a San Francisco-based independent research lab Midjourney, Inc. Midjourney generates images from natural language descriptions, called "prompts", similar to OpenAI''s DALL-E and Stable Diffusion.','Midjourney,Illustration','https://www.midjourney.com/home/',0.00,5,'https://aigc.sgp1.cdn.digitaloceanspaces.com/image-37.png');
INSERT INTO products(id,productname,description,tags,url,price,rating,image) VALUES (37,'Spellbook','Spellbook uses GPT-4 and other large language models to review and suggest terms for your contracts, right in Microsoft Word. "Gives you marble to chisel where you didn''t have any." "This seems like the perfect tool to find the comprehensive clause you need for your specific circumstances.','Contract review','https://www.spellbook.legal/',0.00,3,'https://aigc.sgp1.cdn.digitaloceanspaces.com/image-38.png');
INSERT INTO products(id,productname,description,tags,url,price,rating,image) VALUES (38,'LEX.Page','Lex is basically a word processor that comes equipped with artificial intelligence – meaning it''s always there to help you write better, faster, and help escape writer''s block. It does this by offering up suggestions and ideas based on the context of what you''re writing.','Writing','https://lex.page/',0.00,2,'https://aigc.sgp1.cdn.digitaloceanspaces.com/image-39.png');
INSERT INTO products(id,productname,description,tags,url,price,rating,image) VALUES (39,'D-ID','D-ID Creative Reality Studio, a revolutionary tool that uses deep learning technology to bring your ideas to life by creating and animating AI avatars using simple text prompts. Studio. d-id is the go-to video creation platform, Product Overview: With D-ID, you can skip the hassle of traditional video production.','Video generator','https://studio.d-id.com/',0.00,4,'https://aigc.sgp1.cdn.digitaloceanspaces.com/image-40.png');
INSERT INTO products(id,productname,description,tags,url,price,rating,image) VALUES (40,'TaxyAI/Browser Extension','Taxy uses GPT-4 to control your browser and perform repetitive actions on your behalf. Currently it allows you to define ad-hoc instructions. In the future it will also support saved and scheduled workflows. Taxy''s current status is research preview. Many workflows fail or confuse the agent. If you''d like to hack on Taxy to make it better or test it on your own workflows, follow the instructions below to run it locally.','Automation,Pluggin','https://github.com/TaxyAI/browser-extension',0.00,3,'https://aigc.sgp1.cdn.digitaloceanspaces.com/image-41.png');
INSERT INTO products(id,productname,description,tags,url,price,rating,image) VALUES (41,'Motif GPT4-supported Markdown AI dialogue','Motif GPT4-supported Markdown retrieval dialogue open-source tool.','Search,Conversation','https://github.com/motifland',0.00,3,'https://aigc.sgp1.cdn.digitaloceanspaces.com/image-42.png');
INSERT INTO products(id,productname,description,tags,url,price,rating,image) VALUES (42,'FlowGPT','FlowGPT - The Ultimate Interface of Check the ChatGPT conversations and Prompts shared by others They allow you to discover, share, and use Prompts with a vibrant community.','Prompt','https://flowgpt.com/',0.00,3,'https://aigc.sgp1.cdn.digitaloceanspaces.com/image-43.png');
INSERT INTO products(id,productname,description,tags,url,price,rating,image) VALUES (43,'Massive GPT4 Learning Resources','The Ultimate GPT-4 Guide" platform offers an extensive collection of over 100 resources, providing users with comprehensive knowledge on harnessing the power of ChatGPT, the most advanced natural language AI to date. From learning the basics of GPT-3 to exploring the advanced features of ChatGPT-3, the guide covers a wide range of topics, including using GPT-3 for language learning, teaching, and the introduction of GPT-4. With chapters dedicated to understanding GPT-4, using it on ChatGPT, and highlighting its advantages over ChatGPT, the guide equips users with the necessary information to maximize the potential of OpenAI''s latest language model.','Learning,AI course','https://doc.clickup.com/37456139/d/h/13q28b-324/e2a22b0c164b1f9',0.00,3,'https://aigc.sgp1.cdn.digitaloceanspaces.com/image-44.png');
INSERT INTO products(id,productname,description,tags,url,price,rating,image) VALUES (44,'Firelink Streamlit','The Firelink YouTube Video Translation website is an innovative tool that utilizes the power of ChatGPT to generate Chinese subtitles for YouTube videos. It offers a convenient and efficient way to bridge language barriers and reach a wider audience. With its user-friendly interface and accurate translation capabilities, this website is a valuable resource for content creators and viewers alike.','Subtitles,Youtube','https://alexzhangji-firelink-streamlit-webapp-9fdlcc.streamlit.app/',0.00,3,'https://aigc.sgp1.cdn.digitaloceanspaces.com/image-45.png');
INSERT INTO products(id,productname,description,tags,url,price,rating,image) VALUES (45,'ChatGPT Prompts','You will find a rich collection of ChatGPT prompts, creative writing inspiration, and practical techniques. Unleash unlimited creativity and enhance your writing efficiency and quality.','Prompt,Prompt language','https://prompts.fresns.cn/',0.00,3,'https://aigc.sgp1.cdn.digitaloceanspaces.com/image-47.png');
INSERT INTO products(id,productname,description,tags,url,price,rating,image) VALUES (46,'ChuanhuChatGPT','This tool provides several helpful features for better control of ChatGPT. Users can utilize the System Prompt for improved guidance. They can also select specific prompts from a collection file using Prompt Templates. If the generated response is unsatisfactory, users can easily regenerate it using the 🔄 Regenerate button.','Prompt','https://huggingface.co/spaces/JohnSmith9982/ChuanhuChatGPT',0.00,3,'https://aigc.sgp1.cdn.digitaloceanspaces.com/image-48.png');
INSERT INTO products(id,productname,description,tags,url,price,rating,image) VALUES (47,'Flowful','Flowful is a company whose mission is to keep people focused for as long as possible. They do this by procedurally generating ambient music using AI which stops focus drift and enables the use of music to block distractions.','Music generator','https://www.flowful.app/player',0.00,3,'https://aigc.sgp1.cdn.digitaloceanspaces.com/image-49.png');
INSERT INTO products(id,productname,description,tags,url,price,rating,image) VALUES (48,'Midjourney Keyword Reference','Github user consolidating a very comprehensive Midjourney keyword reference for everyone. It is a reference containing Styles and Keywords that you can use with MidJourney AI. There are also pages showing resolution comparison, image weights, and much more.','Midjourney,Image generator,Prompt','https://github.com/willwulfken/MidJourney-Styles-and-Keywords-Reference',0.00,4,'https://aigc.sgp1.cdn.digitaloceanspaces.com/image-50.png');
INSERT INTO products(id,productname,description,tags,url,price,rating,image) VALUES (49,'lib.KALOS.art','World''s Largest Collection of. Artist Styles, Genres/Mediums. Cover all Popular. Image Generation Models.','Midjourney,Prompt,Artist','https://lib.kalos.art/',0.00,4,'https://aigc.sgp1.cdn.digitaloceanspaces.com/image-51.png');
INSERT INTO products(id,productname,description,tags,url,price,rating,image) VALUES (50,'Explain AI','This site serves as an invaluable instruction manual for ChatGPT, providing all the necessary prompt keywords to enhance your interactions with the language model. It offers a comprehensive list of prompts and instructions that enable users to generate specific and desired responses from ChatGPT. With this resourceful guide, users can unlock the full potential of ChatGPT and create engaging and meaningful conversations.','ChatGPT,Prompt','https://www.explainthis.io/zh-hans/chatgpt',0.00,3,'https://aigc.sgp1.cdn.digitaloceanspaces.com/image-52.png');
INSERT INTO products(id,productname,description,tags,url,price,rating,image) VALUES (51,'AI Adventure Game by Yayapipi','In this AI powered game, you''ll play as a brave adventurer exploring mysterious underground cities, battling dangerous monsters, and solving various puzzles. With the latest AI technology, the game''s dialogue and scenarios will automatically generate based on your answers and choices, providing you with a truly free and diverse experience.','Game','https://yayapipi.itch.io/chatgpt-adventure',0.00,3,'https://aigc.sgp1.cdn.digitaloceanspaces.com/image-53.png');
INSERT INTO products(id,productname,description,tags,url,price,rating,image) VALUES (52,'Node.js client for the official ChatGPT API','A well-encapsulated ChatGPT','ChatGPT,API','https://github.com/transitive-bullshit/chatgpt-api',0.00,3,'https://aigc.sgp1.cdn.digitaloceanspaces.com/image-54.png');
INSERT INTO products(id,productname,description,tags,url,price,rating,image) VALUES (53,'AI Creator Hub - Free AI Tools Built for Creators by Kajabi','Kajabi is the leading all-in-one platform for creator-led businesses. Kajabi helps people turn their knowledge into a sustainable online business by diversifying their revenue streams with digital products and services including (but not limited to) online courses, online communities, and coaching programs.','Marketing','https://kajabi.com/aicreatorhub',0.00,3,'https://aigc.sgp1.cdn.digitaloceanspaces.com/image-55.png');
INSERT INTO products(id,productname,description,tags,url,price,rating,image) VALUES (54,'Miro AI','Miro AI - AI capabilities including brainstorming and mind mapping','Mind map,Brainstorming','https://miro.com/ai/',0.00,3,'https://aigc.sgp1.cdn.digitaloceanspaces.com/image-56.png');
INSERT INTO products(id,productname,description,tags,url,price,rating,image) VALUES (55,'Whimsical AI','Whimsical AI helps with brainstorming by providing inspiration and ideas in seconds. You can ask a question, get up to five different answers and then go deeper into each answer just by clicking on a branch in your mind map.','Mind map','https://whimsical.com/ai-mind-maps',0.00,3,'https://aigc.sgp1.cdn.digitaloceanspaces.com/image-57.png');
INSERT INTO products(id,productname,description,tags,url,price,rating,image) VALUES (56,'Logoscapes AI','Logoscapes - Embed your logo into your artwork for marketing purposes','Logo,Marketing','https://logoscapes.ai/',0.00,3,'https://aigc.sgp1.cdn.digitaloceanspaces.com/image-58.png');
INSERT INTO products(id,productname,description,tags,url,price,rating,image) VALUES (57,'Pebblely AI','Pebblely AI Product Photography - Create beautiful product photos in seconds with AI, replacing backgrounds and more','Marketing,Background edit','https://pebblely.com/',0.00,3,'https://aigc.sgp1.cdn.digitaloceanspaces.com/image-59.png');
INSERT INTO products(id,productname,description,tags,url,price,rating,image) VALUES (58,'Codeverter','This tool offers the convenience of converting code to your preferred programming language. It allows users to seamlessly translate code snippets from one programming language to another, saving time and effort in rewriting or adapting code. With this versatile tool, developers can easily switch between programming languages while maintaining the functionality and logic of their code.','Programming','https://codeverter.vercel.app/',0.00,3,'https://aigc.sgp1.cdn.digitaloceanspaces.com/image-60.png');
INSERT INTO products(id,productname,description,tags,url,price,rating,image) VALUES (59,'scrol.ai','Corpora supports bulk uploads, document sharing, and multi-user collaboration—making it ideal for teams and individuals who desire instant access to information through natural language queries.','Conversation','https://www.scrol.ai',0.00,3,'https://aigc.sgp1.cdn.digitaloceanspaces.com/image-61.png');
INSERT INTO products(id,productname,description,tags,url,price,rating,image) VALUES (60,'ChatMind','ChatMind is an innovative platform that utilizes AI to generate mind maps through interactive dialogue. Users can engage in conversations with the AI, sharing their ideas and thoughts, and in return, the AI generates visual mind maps that organize and connect those concepts. This AI-powered approach simplifies the process of brainstorming, planning, and organizing information, offering a dynamic and intuitive tool for visual thinking and idea exploration.','Mind map','https://www.chatmind.tech/',0.00,3,'https://aigc.sgp1.cdn.digitaloceanspaces.com/image-62.png');
INSERT INTO products(id,productname,description,tags,url,price,rating,image) VALUES (61,'ChatYoutube','Chat YouTube is an AI tool that enables users to interact with YouTube videos by having a chat conversation with them. The tool is designed to allow users to summarize the video, ask questions, and engage in other types of conversations.','Youtube,Summary','https://chatyoutube.com/',0.00,3,'https://aigc.sgp1.cdn.digitaloceanspaces.com/image-63.png');
INSERT INTO products(id,productname,description,tags,url,price,rating,image) VALUES (62,'Reccap','Reccap - Make YouTube videos browsable by turning them into articles with images','Youtube,Summary','https://reccap.it/',0.00,3,'https://aigc.sgp1.cdn.digitaloceanspaces.com/image-64.png');
INSERT INTO products(id,productname,description,tags,url,price,rating,image) VALUES (63,'Whiteout.ai','Writeout.ai, offers an exceptional solution for generating accurate subtitles from audio using the advanced Whisper technology. By leveraging Whisper''s cutting-edge speech recognition capabilities, Story AI enables users to effortlessly transcribe audio files, podcasts, videos, or any other form of spoken content into text-based subtitles. With Story AI, content creators, businesses, and individuals can enhance accessibility, improve user engagement, and streamline their workflows by easily adding subtitles to their multimedia content.','Subtitles,Sound edit','https://writeout.ai/transcribe',0.00,3,'https://aigc.sgp1.cdn.digitaloceanspaces.com/image-65.png');
INSERT INTO products(id,productname,description,tags,url,price,rating,image) VALUES (64,'TR-ChatGPTY','This site offers a unique experience where users can create drumbeats from text using the power of AI. By inputting text, the site''s AI algorithms analyze the linguistic patterns and generate corresponding drum patterns, resulting in dynamic and rhythmic compositions. With this innovative approach, users can explore the intersection of language and music, unleashing their creativity and transforming text into engaging drumbeats.','Music generator','https://huggingface.co/spaces/naotokui/TR-ChatGPT',0.00,3,'https://aigc.sgp1.cdn.digitaloceanspaces.com/image-66.png');
INSERT INTO products(id,productname,description,tags,url,price,rating,image) VALUES (65,'GPTZero','GPTZero - Check if content was generated by ChatGPT','AI check','https://gptzero.me/',0.00,3,'https://aigc.sgp1.cdn.digitaloceanspaces.com/image-67.png');
INSERT INTO products(id,productname,description,tags,url,price,rating,image) VALUES (66,'Optimize your Prompt on Streamlit','Streamlit - Optimize your prompts','Prompt,Prompt optimization','https://promptboost.streamlit.app/',0.00,3,'https://aigc.sgp1.cdn.digitaloceanspaces.com/image-68.png');
INSERT INTO products(id,productname,description,tags,url,price,rating,image) VALUES (67,'Ask ChatGPT using Xiaomi AI speaker (gpt-3.5-turbo)','This repository provides a convenient solution for utilizing ChatGPT with Xiaomi AI speakers, specifically leveraging the gpt-3.5-turbo model. By integrating this repository, users can seamlessly interact with ChatGPT using their Xiaomi AI speakers, enabling natural language conversations and obtaining responses powered by the advanced language capabilities of the model. This integration opens up new possibilities for voice-based AI interactions and extends the functionality of Xiaomi AI speakers.','Hardware,Voice conversation','https://github.com/yihong0618/xiaogpt',0.00,3,'https://aigc.sgp1.cdn.digitaloceanspaces.com/image-69.png');
INSERT INTO products(id,productname,description,tags,url,price,rating,image) VALUES (68,'RCT.ai','RCT.ai is an AI engine based on deep reinforcement learning technology. The Chaos Box algorithm is capable of analyzing real-time inputs from players and dynamically generating NPC''s interactive responses and new storylines. Without the need for any scripts, it can control the behavioral logic of NPCs in the game and enable them to spontaneously exhibit highly intelligent behavior.','Game,NPC','https://rct.ai/zh-hans/chaos-box',0.00,3,'https://aigc.sgp1.cdn.digitaloceanspaces.com/image-70.png');
INSERT INTO products(id,productname,description,tags,url,price,rating,image) VALUES (69,'AI Qiaomu','Explore a comprehensive collection of categorized ChatGPT prompts, creative writing inspirations, and practical techniques. Let us help you unlock boundless creativity and enhance your writing efficiency and quality.','ChatGPT','http://ai.qiaomu.pro/',0.00,4,'https://aigc.sgp1.cdn.digitaloceanspaces.com/image-71.png');
INSERT INTO products(id,productname,description,tags,url,price,rating,image) VALUES (70,'Wind and Rain - Bilingual E-Book Translation Service','Bilingual e-book translation service product','Translation,Digital book,ChatGPT','https://fsys.app/',0.00,4,'https://aigc.sgp1.cdn.digitaloceanspaces.com/image-72.png');
INSERT INTO products(id,productname,description,tags,url,price,rating,image) VALUES (71,'ChatGPT Prompt Debugging Tool','Dyno is a powerful prompt debugging tool designed specifically for ChatGPT. It empowers users to fine-tune and optimize their prompts for more accurate and desired responses. With Dyno, users can iterate and experiment with different prompts, observe the model''s behavior, and make informed adjustments to enhance the quality of their interactions with ChatGPT.','Prompt,ChatGPT','https://embed.trydyno.com/',0.00,3,'https://aigc.sgp1.cdn.digitaloceanspaces.com/image-73.png');
INSERT INTO products(id,productname,description,tags,url,price,rating,image) VALUES (72,'yihong0618/bilingual_book_maker','yihong0618/bilingual_book_maker - Translate English e-books and display them in bilingual format','Digital book,Translation','https://github.com/yihong0618/bilingual_book_maker',0.00,3,'https://aigc.sgp1.cdn.digitaloceanspaces.com/image-75.png');
INSERT INTO products(id,productname,description,tags,url,price,rating,image) VALUES (73,'Make Amazon Alexa smarter with ChatGPT RobertDoufu/aichat','Let Amazon Alexa become smarter with ChatGPT
 RobertDoufu/aichat','ChatGPT,Intelligent music box','https://github.com/RobertDoufu/aichat',0.00,3,'https://aigc.sgp1.cdn.digitaloceanspaces.com/image-76.png');
INSERT INTO products(id,productname,description,tags,url,price,rating,image) VALUES (74,'Mokker AI - Instant AI Background Replacement','Mokker AI - AI background removal for professional product images','Background edit,Product map','https://mokker.ai/',0.00,3,'https://aigc.sgp1.cdn.digitaloceanspaces.com/image-77.png');
INSERT INTO products(id,productname,description,tags,url,price,rating,image) VALUES (75,'AI Phind','Phind is a search engine that simply tells users what the answers are. Optimized for developers and technical questions, Phind instantly answers questions with simple explanations and relevant code snippets from the web.','Programming,Search engine','https://phind.com/',0.00,3,'https://aigc.sgp1.cdn.digitaloceanspaces.com/image-78.png');
INSERT INTO products(id,productname,description,tags,url,price,rating,image) VALUES (76,'MakeLogoAI','MakeLogoAI generates unique logos with AI. A cost-effective alternative to designer logos, MakeLogoAI generates high-quality logo designs that you can use for your project or business.','Logo','https://makelogo.ai/',0.00,3,'https://aigc.sgp1.cdn.digitaloceanspaces.com/image-79.png');
INSERT INTO products(id,productname,description,tags,url,price,rating,image) VALUES (77,'ElevenLabs || Prime Voice AI','ElevenLabs is a voice technology research company developing the most compelling and lifelike AI speech software for publishers and creators. The most realistic and versatile AI speech software, ever. Eleven brings the most compelling, rich and lifelike voices to creators and publishers seeking the ultimate tools for storytelling.','Voice edit','https://beta.elevenlabs.io/speech-synthesis',0.00,3,'https://aigc.sgp1.cdn.digitaloceanspaces.com/image-80.png');
INSERT INTO products(id,productname,description,tags,url,price,rating,image) VALUES (78,'AI SEO Outlines','AI SEO Outlinehelps to generate SEO-friendly content quickly and easily. It takes a keyword or topic as input and produces an SEO title, meta description, article outline, LSI keywords (with search volume), Frequently Asked Questions (FAQs) and image suggestions as output.','SEO','https://aiseooutlines.com/',0.00,3,'https://aigc.sgp1.cdn.digitaloceanspaces.com/image-81.png');
INSERT INTO products(id,productname,description,tags,url,price,rating,image) VALUES (79,'SimpRead - Simplify Web Pages','SimpRead - Input URL and get the article and summary','Reading,Summary','https://beta.simp.red/',0.00,4,'https://aigc.sgp1.cdn.digitaloceanspaces.com/image-82.png');
INSERT INTO products(id,productname,description,tags,url,price,rating,image) VALUES (80,'summarize.tech','Get a summary of any lengthy YouTube video effortlessly with the help of ChatGPT. Whether it''s a lecture, live event, or a government meeting, this powerful tool can process the content and provide you with a concise summary. By leveraging the capabilities of ChatGPT, you can save time and quickly grasp the key points and insights from extensive video content.','Youtube,summary','https://www.summarize.tech/',0.00,3,'https://aigc.sgp1.cdn.digitaloceanspaces.com/image-83.png');
INSERT INTO products(id,productname,description,tags,url,price,rating,image) VALUES (81,'Defined.ai','Defined.ai is enabling AI creators of the future, from those building their first boot-strapped models, to those fine-tuning complex AI projects. Defined.ai hosts the leading online marketplace where it''s possible to buy, sell or commission off-the-shelf or custom-ordered AI data, tools and models, and offers professional services to help deliver success in complex machine learning projects.','Database','https://www.definite.app/',0.00,3,'https://aigc.sgp1.cdn.digitaloceanspaces.com/image-84.png');
INSERT INTO products(id,productname,description,tags,url,price,rating,image) VALUES (82,'ChatGPT Cheat Sheet & Quick Reference','This cheat sheet serves as a valuable resource, compiling prompts and tips from around the world to help users maximize the effectiveness of ChatGPT. It provides a comprehensive guide on how to engage with the language model, offering insights and strategies for generating more accurate and helpful responses. Whether you''re a beginner or an experienced user, this cheat sheet is a handy tool to enhance your interactions and make the most out of ChatGPT.','AI course','https://quickref.me/chatgpt',0.00,3,'https://aigc.sgp1.cdn.digitaloceanspaces.com/image-85.png');
INSERT INTO products(id,productname,description,tags,url,price,rating,image) VALUES (83,'AudioStack','AudioStack is the first AI audio infrastructure that makes scalable audio production possible, 100 % faster and 99% cheaper. Build your professional audio creation workflow from ingesting written text to fully produced audio experiences in just seconds.','Voice generator','https://www.audiostack.ai/',0.00,3,'https://aigc.sgp1.cdn.digitaloceanspaces.com/image-86.png');
INSERT INTO products(id,productname,description,tags,url,price,rating,image) VALUES (84,'AIGC Moments','AIGC Moments is a collaborative library of Chinese AIGC use cases starting with observing use cases. It aims to showcase the potential of AI and its applications in various scenarios. Their database comes with wide range of use cases, from natural language processing to image generation, to help you better understand the power of AI and how it can be applied to your needs.','AI usecase,AI course','https://www.aigcmoments.com/',0.00,3,'https://aigc.sgp1.cdn.digitaloceanspaces.com/image-87.png');
INSERT INTO products(id,productname,description,tags,url,price,rating,image) VALUES (85,'Character.AI','Character.AI is a site that uses a neural language model to reads huge amounts of text and respond to prompts using that information. Anyone can create a character on the site, and they can be fictional or based on real people, dead or alive.','Conversation,Chatbot','https://beta.character.ai/',0.00,4,'https://aigc.sgp1.cdn.digitaloceanspaces.com/image-88.png');
INSERT INTO products(id,productname,description,tags,url,price,rating,image) VALUES (86,'Replicate','pharmapsychotic/clip-interrogator - Reverse-engineer image prompts with API on Replicate','Prompt,Reverse engineering','https://replicate.com/pharmapsychotic/clip-interrogator',0.00,3,'https://aigc.sgp1.cdn.digitaloceanspaces.com/image-89.png');
INSERT INTO products(id,productname,description,tags,url,price,rating,image) VALUES (87,'Scribble Diffusion','Scribble Diffusion is a free and open-source AI-powered web app that lets you draw a rough sketch, add a text prompt, to bring your doodles to life. You can then download the AI-generated image to use however you need.','Illustration,SD','https://scribblediffusion.com/',0.00,4,'https://aigc.sgp1.cdn.digitaloceanspaces.com/image-90.png');
INSERT INTO products(id,productname,description,tags,url,price,rating,image) VALUES (88,'MidJourney Prompt Tool','The MidJourney Prompt Tool is a valuable resource designed to enhance the capabilities of language models like GPT-3 and GPT-4. It provides users with a convenient way to guide the output of the models by inserting prompts at specific points during the generation process. With this tool, users can fine-tune and refine the responses generated by the language models, ensuring more accurate and contextually relevant outputs for a wide range of applications. Whether it''s controlling the tone, style, or specific information in the generated text, the MidJourney Prompt Tool empowers users with greater control and customization options.','Midjourney,Prompt','https://prompt.noonshot.com/',0.00,3,'https://aigc.sgp1.cdn.digitaloceanspaces.com/image-91.png');
INSERT INTO products(id,productname,description,tags,url,price,rating,image) VALUES (89,'From zero to ChatGPT','The website "From zero to ChatGPT" is an invaluable resource for anyone interested in creating their own ChatGPT models. The tutorial takes users through a comprehensive step-by-step process, starting from the basics and gradually diving into more advanced concepts. With clear explanations, code examples, and practical exercises, this website equips aspiring developers with the knowledge and tools to build their very own conversational AI models using ChatGPT.','AI course','https://xv44586.github.io/2023/01/09/zero-to-chatgpt/',0.00,3,'https://aigc.sgp1.cdn.digitaloceanspaces.com/image-92.png');
INSERT INTO products(id,productname,description,tags,url,price,rating,image) VALUES (90,'Stocking.ai','Stockimg AI - AI-generated logos, book covers, posters, and more','Marketing','https://stockimg.ai/',0.00,3,'https://aigc.sgp1.cdn.digitaloceanspaces.com/image-93.png');
INSERT INTO products(id,productname,description,tags,url,price,rating,image) VALUES (91,'Lexica Aperture','Lexica Aperture is an AI tool designed to generate photorealistic images. It has a simple, user-friendly interface with options to customize the image from a range of parameters. This includes choosing the dimensions, adding text, and making variations.','Illustration','https://lexica.art/aperture',0.00,3,'https://aigc.sgp1.cdn.digitaloceanspaces.com/image-94.png');
INSERT INTO products(id,productname,description,tags,url,price,rating,image) VALUES (92,'Mubert','Mubert - Thousands of staff-picked, AI-generated royalty-free music tracks for streaming, videos, podcasts, commercial use, and online content','Music generator','https://mubert.com/',0.00,3,'https://aigc.sgp1.cdn.digitaloceanspaces.com/image-95.png');
INSERT INTO products(id,productname,description,tags,url,price,rating,image) VALUES (93,'dair-ai/Prompt-Engineering-Guide','Prompt engineering is a relatively new discipline for developing and optimizing prompts to efficiently use language models (LMs) for a wide variety of applications and research topics. Motivated by the high interest in developing with LLMs, we have created this new prompt engineering guide that contains all the latest papers, learning guides, lectures, references, and tools related to prompt engineering for LLMs.','Prompt','https://github.com/dair-ai/Prompt-Engineering-Guide',0.00,3,'https://aigc.sgp1.cdn.digitaloceanspaces.com/image-96.png');
INSERT INTO products(id,productname,description,tags,url,price,rating,image) VALUES (94,'Beta Tome','Launching in beta, Tome''s AI enables creators to generate entire narratives from scratch, complete with intelligent titles, outlines, pagination, page layouts and page content supported by GPT-3 and AI-generated images.','Prompt,PPT','https://beta.tome.app/',0.00,3,'https://aigc.sgp1.cdn.digitaloceanspaces.com/image-97.png');
INSERT INTO products(id,productname,description,tags,url,price,rating,image) VALUES (95,'Chat Content Simplifier','his tool is a simplified chat content solution powered by OpenAI''s technology. It allows users to streamline and condense chat conversations into more concise and coherent forms. By leveraging OpenAI''s capabilities, the tool enhances readability and comprehension, making it easier to understand and extract valuable information from chat discussions.','Summary,Chat','https://chat-simplifier.imzbb.cc/zh',0.00,3,'https://aigc.sgp1.cdn.digitaloceanspaces.com/image-98.png');
INSERT INTO products(id,productname,description,tags,url,price,rating,image) VALUES (96,'Artifact','Artifact is a free app that learns your interests and brings you the best articles the web has to offer. Discover interesting articles and stay on top of important headlines. Find new content others are talking about, share your own thoughts, and vote on the best takes. Read on your own terms with a reader mode and automatic dark mode for websites.','App,News','https://artifact.news/',0.00,3,'https://aigc.sgp1.cdn.digitaloceanspaces.com/image-99.png');
INSERT INTO products(id,productname,description,tags,url,price,rating,image) VALUES (97,'ChatGPT Chinese Training Guide','This repository offers a ChatGPT Chinese Training Guide, providing step-by-step instructions on how to train ChatGPT to understand and respond in Chinese. It serves as a comprehensive resource, guiding users through the process of training the model and enabling it to effectively comprehend and generate Chinese language responses. With this valuable guide, users can customize ChatGPT to better cater to Chinese language conversations and create more interactive and engaging experiences.','Prompt','https://github.com/PlexPt/awesome-chatgpt-prompts-zh',0.00,4,'https://aigc.sgp1.cdn.digitaloceanspaces.com/image-100.png');
INSERT INTO products(id,productname,description,tags,url,price,rating,image) VALUES (98,'Rationale - A Decision Analysis AI','Rationale is an innovative AI tool designed to support individuals and businesses in navigating difficult decision-making processes. By leveraging advanced technologies such as GPT and in-context learning algorithms, Rationale provides a comprehensive analysis of pros and cons, generates SWOT analyses, and conducts various analytical frameworks to assist users in evaluating their options effectively.','Strategy','https://rationale.jinaai.cn/',0.00,3,'https://aigc.sgp1.cdn.digitaloceanspaces.com/image-101.png');
INSERT INTO products(id,productname,description,tags,url,price,rating,image) VALUES (99,'Enter the city name and days, generate a travel guide','Roamaround app uses the latest technology to create personalized travel plans that are tailored to users preferences and interests. With Roamaround, users will never have to spend hours researching and planning your next vacation again.','Travel','https://www.roamaround.io/',0.00,3,'https://aigc.sgp1.cdn.digitaloceanspaces.com/image-102.png');
INSERT INTO products(id,productname,description,tags,url,price,rating,image) VALUES (100,'Synthesia | #1 AI Video Generation Platform','Synthesia - AI video generation platform with pay-per-text AI video creation','Video generator','https://www.synthesia.io/',0.00,3,'https://aigc.sgp1.cdn.digitaloceanspaces.com/image-103.png');
INSERT INTO products(id,productname,description,tags,url,price,rating,image) VALUES (101,'Old Photo Restoration Face Photo Restorer','Face Photo Restorer - Restore old photos of faces','Photo edit','https://www.restorephotos.io/',0.00,3,'https://aigc.sgp1.cdn.digitaloceanspaces.com/image-104.png');
INSERT INTO products(id,productname,description,tags,url,price,rating,image) VALUES (102,'Immersive Translation - Chrome Web Store','Immersive Translation is a pluggin for web bilingual translation, completely free to use, supports Deepl/Google/Bing/Tencent/Youdao, etc.','Translation,Digital book','https://chrome.google.com/webstore/detail/immersive-translate/bpoadfkcbjbfhfodiogcnhhhpibjhbnh/related',0.00,5,'https://aigc.sgp1.cdn.digitaloceanspaces.com/image-105.png');
INSERT INTO products(id,productname,description,tags,url,price,rating,image) VALUES (103,'Perplexity AI - Conversational Search AI: Ask Anything','Perplexity AI - AI-powered conversational search','Search engine','https://www.perplexity.ai/',0.00,4,'https://aigc.sgp1.cdn.digitaloceanspaces.com/image-106.png');
INSERT INTO products(id,productname,description,tags,url,price,rating,image) VALUES (104,'Xpression Camera','xpression camera is an award winning virtual camera app which allows users to instantly transform into anyone or anything with a face with a single photo without any processing time. xpression camera enables users to redefine their onscreen persona in real-time, while chatting on apps like Zoom, live streaming on Twitch, or creating a YouTube video.','VR','https://xpressioncamera.com/',0.00,3,'https://aigc.sgp1.cdn.digitaloceanspaces.com/image-107.png');
INSERT INTO products(id,productname,description,tags,url,price,rating,image) VALUES (105,'Prompt Hero','PromptHero is the best search engine to look for Stable Diffusion prompts, Midjourney prompts and DALL-E 2 prompts. We''re building a community of amazing prompt engineers and creatives that are creating breathtaking AI generated art and AI generated images.','Prompt','https://prompthero.com/',0.00,3,'https://aigc.sgp1.cdn.digitaloceanspaces.com/image-108.png');
INSERT INTO products(id,productname,description,tags,url,price,rating,image) VALUES (106,'Supernormal','AI-generated Meeting Minutes with Supernormal - Let AI write your meeting notes.','Meeting minutes','https://supernormal.com/',0.00,3,'https://aigc.sgp1.cdn.digitaloceanspaces.com/image-110.png');
INSERT INTO products(id,productname,description,tags,url,price,rating,image) VALUES (107,'WatchNow AI','Movie and Show recommendations powered by AI - WatchNow AI','Entertainment,Movie','https://www.watchnowai.com/',0.00,3,'https://aigc.sgp1.cdn.digitaloceanspaces.com/image-111.png');
INSERT INTO products(id,productname,description,tags,url,price,rating,image) VALUES (108,'AIGC Weekly Newsletter','AIGC Weekly Newsletter platform is a comprehensive resource that provides curated updates on the latest advancements, research, and trends in the field of artificial intelligence. It delivers a concise summary of key developments, industry news, and noteworthy articles directly to subscribers'' inboxes every week. Stay informed and up-to-date with the rapidly evolving world of AI through this valuable newsletter platform.','Media,AI course','https://op7418.zhubai.love/',0.00,3,'https://aigc.sgp1.cdn.digitaloceanspaces.com/image-112.png');
INSERT INTO products(id,productname,description,tags,url,price,rating,image) VALUES (109,'Free online text-to-speech - TTSMaker','TTSMaker is an exceptional online tool that provides a free and convenient solution for converting text into speech. With its user-friendly interface and high-quality audio output, it allows users to easily transform written content into natural-sounding audio files. Whether for accessibility purposes, content creation, or personal use, TTSMaker offers a reliable and efficient text-to-speech conversion experience.','Voice generator','https://ttsmaker.com/zh-cn',0.00,3,'https://aigc.sgp1.cdn.digitaloceanspaces.com/image-113.png');
INSERT INTO products(id,productname,description,tags,url,price,rating,image) VALUES (110,'Yuan Cheng Xiang ChatImg','Upload an image and chat based on the image question.','Image recognition','http://chatimg.aixiaoqingxu.com/',0.00,3,'https://aigc.sgp1.cdn.digitaloceanspaces.com/image-114.png');
INSERT INTO products(id,productname,description,tags,url,price,rating,image) VALUES (111,'POE','Poe is a service developed by Quora. It allows users to ask questions and obtain answers from a range of AI bots built on top of large language models (LLMs), including those from ChatGPT developer OpenAI, and other companies like Anthropic and Neeva.','Conversation','https://poe.com/',0.00,5,'https://aigc.sgp1.cdn.digitaloceanspaces.com/image-115.png');
INSERT INTO products(id,productname,description,tags,url,price,rating,image) VALUES (112,'Glarity','This is an open-source extension that uses the power of ChatGPT to generate summaries of web page content, including Google search results, YouTube videos, and other web pages.','Summary,Pluggin,ChatGPT','https://chrome.google.com/webstore/detail/glarity-summary-for-googl/cmnlolelipjlhfkhpohphpedmkfbobjc',0.00,5,'https://aigc.sgp1.cdn.digitaloceanspaces.com/image-116.png');
INSERT INTO products(id,productname,description,tags,url,price,rating,image) VALUES (113,'Glasp','Glasp is a social web highlighter that people can use to highlight and organize quotes and ideas from the web without switching back and forth between screens, and access other like-minded people’s learning at the same time. Leave your digital legacy for humanity, while working for yourself','Summary,AI bookmark','https://glasp.co/',0.00,5,'https://aigc.sgp1.cdn.digitaloceanspaces.com/image-117.png');
INSERT INTO products(id,productname,description,tags,url,price,rating,image) VALUES (114,'CourseAI','CourseAI is an innovative platform that enables users to effortlessly transform any subject into a captivating online course. With the power of AI, their authoring tool simplifies the course creation process, freeing users to focus on their content and expertise. By leveraging CourseAI, educators and content creators can easily craft engaging and high-quality online courses, delivering valuable knowledge and experiences to learners worldwide.','AI course','https://courseai.co/',0.00,3,'https://aigc.sgp1.cdn.digitaloceanspaces.com/image-118.png');
INSERT INTO products(id,productname,description,tags,url,price,rating,image) VALUES (115,'Taskade','Taskade is a free cross-platform team collaboration tool that now includes an AI assistant feature.','Workflow','https://taskade.com',0.00,3,'https://aigc.sgp1.cdn.digitaloceanspaces.com/image-119.png');
INSERT INTO products(id,productname,description,tags,url,price,rating,image) VALUES (116,'Dify.ai','Dify provides a smooth experience for model access, context embedding, cost control and data annotation. Whether for internal team use or product development, you can easily create AI applications.','SaaS','www.dify.ai',0.00,3,'https://aigc.sgp1.cdn.digitaloceanspaces.com/image-120.png');
INSERT INTO products(id,productname,description,tags,url,price,rating,image) VALUES (117,'ChatALL','An application that allows you to submit a question to multiple large models simultaneously and view the results, supporting nearly all major models available in the market.','LLM,Test','https://github.com/sunner/ChatALL/releases',0.00,3,'https://aigc.sgp1.cdn.digitaloceanspaces.com/image-121.png');
INSERT INTO products(id,productname,description,tags,url,price,rating,image) VALUES (118,'Newsminimalist','Empower GPT to read and select the most worthwhile news articles each day.','News','https://www.newsminimalist.com/',0.00,3,'https://aigc.sgp1.cdn.digitaloceanspaces.com/image-122.png');
INSERT INTO products(id,productname,description,tags,url,price,rating,image) VALUES (119,'Midjounery 2000 artist style comparison chart','Midjounery author style and works chart v5, v4, etc.','Midjourney,Design','https://docs.google.com/spreadsheets/d/1cm6239gw1XvvDMRtazV6txa9pnejpKkM5z24wRhhFz0/htmlview',0.00,3,'https://aigc.sgp1.cdn.digitaloceanspaces.com/image-123.png');
INSERT INTO products(id,productname,description,tags,url,price,rating,image) VALUES (120,'Midlibrary','Andrei Kovalev''s Midlibrary is a carefully curated collection of hand-picked Midjourney Styles and Midjourney Guide. We are a non-profit educational initiative run by a group of dedicated Midjourney enthusiasts and volunteers.','Midjourney,Design','https://www.midlibrary.io/',0.00,3,'https://aigc.sgp1.cdn.digitaloceanspaces.com/image-124.png');
INSERT INTO products(id,productname,description,tags,url,price,rating,image) VALUES (121,'Chatkit','Chatkit supports Google search, answering factual questions, and avoids ChatGPT made up information (requires Google Search API, tutorial: https://docs.chatkit.app/tools/google-search.html). It also supports Text to Image and image upscaling. Apply API for free at https://replicate.com/account. It offers image compression by using the Tinypng API interface. Register for free at https://tinypng.com/developers. It supports document conversations similar to ChatPDF. It also has features like voice input and text-to-speech (TTS) playback. Common features include using your own OpenAI key, custom prompts/system prompts, data import/export, search through conversation history, and recommended related questions.','ChatGPT','https://chatkit.app/',0.00,3,'https://aigc.sgp1.cdn.digitaloceanspaces.com/image-125.png');
INSERT INTO products(id,productname,description,tags,url,price,rating,image) VALUES (122,'TextGPT','To add an iMessage contact and start a conversation with ChatGPT, simply add "textgpt@icloud.com" as the contact. You can also use it to generate images with Dall-E by prefixing your text with 🖌️','ChatGPT','https://www.textgpt.chat/',0.00,3,'https://aigc.sgp1.cdn.digitaloceanspaces.com/image-126.png');
INSERT INTO products(id,productname,description,tags,url,price,rating,image) VALUES (123,'Baidu''s AI Art and Creative Assistance Platform','Baidu''s AI Art and Creative Assistance Platform is a groundbreaking solution that harnesses the power of artificial intelligence to revolutionize the world of art and creativity. By leveraging advanced algorithms and deep learning models, Baidu''s platform provides artists with innovative tools and resources to enhance their artistic process and create stunning visual content. From generating realistic digital paintings to assisting in design and composition, Baidu''s AI Art and Creative Assistance Platform empowers artists to explore new possibilities and unleash their creative potential.','AI Design,Creativity','https://yige.baidu.com/',0.00,3,'https://aigc.sgp1.cdn.digitaloceanspaces.com/image-127.png');
INSERT INTO products(id,productname,description,tags,url,price,rating,image) VALUES (124,'Feishu Miaoji','A super tool that can transcribe both audio and video content into text. It quickly organizes every sharing session into text format, and it can even automatically recognize the speaker''s voice tone. This amazing tool is completely free! No need to worry about any charges!','Notes taking','https://visioncap.feishu.cn/minutes/home',0.00,3,'https://aigc.sgp1.cdn.digitaloceanspaces.com/image-128.png');
INSERT INTO products(id,productname,description,tags,url,price,rating,image) VALUES (125,'SnackPrompt','PromptHub on GitHub, where you can create and share your own prompts. It allows you to explore popular prompts based on weekly or monthly popularity.','Prompt','https://snackprompt.com/',0.00,3,'https://aigc.sgp1.cdn.digitaloceanspaces.com/image-129.png');
INSERT INTO products(id,productname,description,tags,url,price,rating,image) VALUES (126,'Finchat','FinChat.io is powered by ChatGPT. Using AI, FinChat generates answers to questions about public companies and investors. To generate accurate answers, FinChat provides reasoning, sources and data. Summarize Microsoft''s last quarter with a focus on the cloud business.','Finance,AI App','https://finchat.io/',0.00,3,'https://aigc.sgp1.cdn.digitaloceanspaces.com/image-130.png');
INSERT INTO products(id,productname,description,tags,url,price,rating,image) VALUES (127,'Godmode','GodMode web is an innovative platform that embraces the UI implementation reminiscent of AutoGPT and BabyAGI concepts. With its own API key requirement, users gain access to a powerful toolkit for developing advanced conversational AI models. By combining a user-friendly interface with the potential for sophisticated AI interactions, GodMode web provides an exciting opportunity for developers to explore and create groundbreaking conversational experiences.','AI Agent','https://godmode.space/',0.00,3,'https://aigc.sgp1.cdn.digitaloceanspaces.com/image-131.png');
INSERT INTO products(id,productname,description,tags,url,price,rating,image) VALUES (128,'Modelscope','This is a Chinese version of Hugging Face. It is built upon the notion of “Model-as-a-Service” (MaaS).The core ModelScope library open-sourced in this repository provides the interfaces and implementations that allow developers to perform model inference, training and evaluation.','AI models,Model repositories,Source code','https://www.modelscope.cn/models',0.00,5,'https://aigc.sgp1.cdn.digitaloceanspaces.com/image-132.png');
INSERT INTO products(id,productname,description,tags,url,price,rating,image) VALUES (129,'Hugging Face','AIGCCommunity Hugging Face – The AI community building the future.','AI community,Source code','https://huggingface.co/',0.00,4,'https://aigc.sgp1.cdn.digitaloceanspaces.com/image-134.png');
INSERT INTO products(id,productname,description,tags,url,price,rating,image) VALUES (130,'Codeium','Codeium is the modern coding superpower, a free code acceleration toolkit built on cutting edge AI technology. Currently, Codeium provides code completion tool in over 20+ languages, with lightning fast speeds and state-of-the-art suggestion quality.','Coding,Programming','www.codeium.com',0.00,4,'https://aigc.sgp1.cdn.digitaloceanspaces.com/image-135.png');
INSERT INTO products(id,productname,description,tags,url,price,rating,image) VALUES (131,'Amymind','Amymind is an innovative AI-generated mind mapping tool that simplifies the process of organizing and visualizing ideas. Powered by advanced AI algorithms, it allows users to input their thoughts and concepts, which are then dynamically structured into interconnected mind maps. With its intuitive interface and intelligent mapping capabilities, Amymind empowers users to brainstorm, plan, and present ideas with ease and clarity.','Mind map','https://amymind.com/',0.00,3,'https://aigc.sgp1.cdn.digitaloceanspaces.com/image-136.png');
INSERT INTO products(id,productname,description,tags,url,price,rating,image) VALUES (132,'Cognosys','Cognosys is an AI-powered agent that enables users to experience the future of AI-driven applications. With Cognosys, users can leverage AI and machine learning capabilities to enhance their applications, making them more intelligent, efficient, and effective.','AI Agent,Productivity tool','https://www.cognosys.ai',0.00,3,'https://aigc.sgp1.cdn.digitaloceanspaces.com/image-137.png');
INSERT INTO products(id,productname,description,tags,url,price,rating,image) VALUES (133,'MacGPT','Access ChatGPT from anywhere on your Mac with the Global feature. Simply activate the Global textfield that pops up in the middle of your screen, and start chatting with ChatGPT.','Client side,ChatGPT','https://www.macgpt.com/',0.00,5,'https://aigc.sgp1.cdn.digitaloceanspaces.com/image-138.png');
INSERT INTO products(id,productname,description,tags,url,price,rating,image) VALUES (134,'Zeeno App','Zeeno supercharges your mobile keyboard using AI. This keyboard extension will let you access ChatGPT and GPT-4 from any text box on your phone. Generate ideas in your text conversations, re-phrase posts in your social media apps, and research or ask for advice in any app you use, all with the tap of a button!','AI keyboard','https://apps.apple.com/app/zeeno-ai-keyboard/id1669725575',0.00,3,'https://aigc.sgp1.cdn.digitaloceanspaces.com/image-139.png');
INSERT INTO products(id,productname,description,tags,url,price,rating,image) VALUES (135,'Moonvy','This is a tool aimed at visualizing and providing editing capabilities for AIGC prompts.','Midjourney,Prompt','https://moonvy.com/apps/ops/',0.00,3,'https://aigc.sgp1.cdn.digitaloceanspaces.com/image-140.png');
